workspace:
  base: /go/src
  path: github.com/qnib/jupyterport

pipeline:
  x86:
      image: golang
      commands:
        - mkdir -p bin/v0.2.4
        - go build -o bin/v0.2.4/jupyterport_x86
  #alpine:
  #  image: golang:alpine
  #  commands:
  #  - mkdir -p bin/v0.2.4
  #  - go build -o bin/v0.2.4/jupyterport_alpine
