kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook-service
spec:
  type: NodePort
  selector:
    app: test-mynotebook-deloyment
  ports:
  - protocol: TCP
    nodePort: 31888
    port: 8888
    targetPort: 8888